# Change 'comments' to true for Disqus comments
#disqus:
#  comments: false
#  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-166176851-1'

menu:
#- {name: 'Projects', folder: 'pages', file: 'projects.html'}
- {name: 'Github', folder: 'pages', file: 'github.html'}
- {name: 'Tutorials', folder: 'pages', file: 'tutorials.html'}
- {name: 'About', folder: 'pages', file: 'about.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://github.com/UrbanoFonseca/'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/urbanofonseca/'}
# - {icon: 'hackerrank', link: 'https://www.hackerrank.com/UrbanoFonseca'}
- {icon: 'envelope', link: 'mailto:l.francisco.urbfonseca@gmail.com'}



# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
